version: '3.7'
services:
  app:
    build: file-saver
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./file-saver/:/home/node/app
      - node_modules:/home/node/app/node_modules
  api:
    build: file-saver-api
    command: sh -c "npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./file-saver-api/:/home/node/app
      - node_modules_two:/home/node/app/node_modules
  mongodb:
    image : mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
volumes:
  node_modules:
  node_modules_two:
 
#  express: # name of the second service
#   build: express-server # specify the directory of the Dockerfile
#   ports:
#   - "3000:3000" #specify ports mapping
#   links:
#   - database # link this service to the database service
 
# database: # name of the third service
#   image: mongo # specify image to build container from
#   ports:
#     - "27017:27017" # specify port forwarding