version: '3.7'
services:
  app:
    build: file-saver
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./file-saver/:/home/node/app
  api:
    build: file-saver-api
    command: sh -c "npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./file-saver-api/:/home/node/app
  mongodb:
    image : mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always